{% set version = '0.5.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-broom
  version: {{ version|replace("-", "_") }}

source:
  fn: broom_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/broom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broom/broom_{{ version }}.tar.gz
  sha256: 4f912b5d9f6b7dfb24793024cdcf47e8c1a70941b907820ad4a53980771868e4

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-backports
    - r-dplyr
    - r-generics >=0.0.2
    - r-nlme
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-backports
    - r-dplyr
    - r-generics >=0.0.2
    - r-nlme
    - r-purrr
    - r-reshape2
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('broom')"           # [not win]
    - "\"%R%\" -e \"library('broom')\""  # [win]

about:
  home: http://github.com/tidyverse/broom
  license: MIT
  summary: Summarizes key information about statistical objects in tidy tibbles. This makes it
    easy to report results, create plots and consistently work with large numbers of
    models at once. Broom provides three verbs that  each provide different types of
    information about a model. tidy() summarizes information about model components
    such as coefficients of a regression. glance() reports information about an entire
    model, such as goodness of fit measures like AIC and BIC. augment() adds information
    about individual observations to a dataset, such as fitted values or influence measures.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
